package shop

import "github.com/ralleh-ai/ralleh-mcp/internal/core/source"

// DefaultRegistry is the first curated shopping source registry. Raw website
// URLs are not accepted by v1 search APIs; callers choose collections and known
// source IDs only.
func DefaultRegistry() source.Registry {
	sources := map[string]source.Source{
		"amazon_api":         {ID: "amazon_api", Name: "Amazon", Domains: []string{"amazon.com"}, SearchTemplate: "https://www.amazon.com/s?k={query}", Modes: []source.Mode{source.ModeAPI}, Priority: 70, Marketplace: true, AffiliateCapable: true},
		"walmart":            {ID: "walmart", Name: "Walmart", Domains: []string{"walmart.com"}, SearchTemplate: "https://www.walmart.com/search?q={query}", Modes: []source.Mode{source.ModeHTMLFetch, source.ModeBrowserVerify}, Priority: 86, Marketplace: true},
		"target":             {ID: "target", Name: "Target", Domains: []string{"target.com"}, SearchTemplate: "https://www.target.com/s?searchTerm={query}", Modes: []source.Mode{source.ModeHTMLFetch, source.ModeBrowserVerify}, Priority: 88},
		"best_buy":           {ID: "best_buy", Name: "Best Buy", Domains: []string{"bestbuy.com"}, SearchTemplate: "https://www.bestbuy.com/site/searchpage.jsp?st={query}", Modes: []source.Mode{source.ModeHTMLFetch, source.ModeBrowserVerify}, Priority: 92},
		"home_depot":         {ID: "home_depot", Name: "Home Depot", Domains: []string{"homedepot.com"}, SearchTemplate: "https://www.homedepot.com/s/{query}", Modes: []source.Mode{source.ModeHTMLFetch, source.ModeBrowserVerify}, Priority: 95},
		"lowes":              {ID: "lowes", Name: "Lowe's", Domains: []string{"lowes.com"}, SearchTemplate: "https://www.lowes.com/search?searchTerm={query}", Modes: []source.Mode{source.ModeHTMLFetch, source.ModeBrowserVerify}, Priority: 92},
		"menards":            {ID: "menards", Name: "Menards", Domains: []string{"menards.com"}, SearchTemplate: "https://www.menards.com/main/search.html?search={query}", Modes: []source.Mode{source.ModeHTMLFetch, source.ModeBrowserVerify}, Priority: 75},
		"ace_hardware":       {ID: "ace_hardware", Name: "Ace Hardware", Domains: []string{"acehardware.com"}, SearchTemplate: "https://www.acehardware.com/search?query={query}", Modes: []source.Mode{source.ModeHTMLFetch, source.ModeBrowserVerify}, Priority: 80},
		"harbor_freight":     {ID: "harbor_freight", Name: "Harbor Freight", Domains: []string{"harborfreight.com"}, SearchTemplate: "https://www.harborfreight.com/search?q={query}", Modes: []source.Mode{source.ModeHTMLFetch, source.ModeBrowserVerify}, Priority: 88},
		"tractor_supply":     {ID: "tractor_supply", Name: "Tractor Supply", Domains: []string{"tractorsupply.com"}, SearchTemplate: "https://www.tractorsupply.com/tsc/search/{query}", Modes: []source.Mode{source.ModeHTMLFetch, source.ModeBrowserVerify}, Priority: 78},
		"northern_tool":      {ID: "northern_tool", Name: "Northern Tool", Domains: []string{"northerntool.com"}, SearchTemplate: "https://www.northerntool.com/search?query={query}", Modes: []source.Mode{source.ModeHTMLFetch, source.ModeBrowserVerify}, Priority: 76},
		"grainger":           {ID: "grainger", Name: "Grainger", Domains: []string{"grainger.com"}, SearchTemplate: "https://www.grainger.com/search?searchQuery={query}", Modes: []source.Mode{source.ModeHTMLFetch, source.ModeBrowserVerify}, Priority: 78},
		"mcmaster_carr":      {ID: "mcmaster_carr", Name: "McMaster-Carr", Domains: []string{"mcmaster.com"}, SearchTemplate: "https://www.mcmaster.com/search?q={query}", Modes: []source.Mode{source.ModeHTMLFetch, source.ModeBrowserVerify}, Priority: 74},
		"zoro":               {ID: "zoro", Name: "Zoro", Domains: []string{"zoro.com"}, SearchTemplate: "https://www.zoro.com/search?q={query}", Modes: []source.Mode{source.ModeHTMLFetch, source.ModeBrowserVerify}, Priority: 72},
		"staples":            {ID: "staples", Name: "Staples", Domains: []string{"staples.com"}, SearchTemplate: "https://www.staples.com/search?query={query}", Modes: []source.Mode{source.ModeHTMLFetch, source.ModeBrowserVerify}, Priority: 80},
		"office_depot":       {ID: "office_depot", Name: "Office Depot", Domains: []string{"officedepot.com"}, SearchTemplate: "https://www.officedepot.com/a/search/?q={query}", Modes: []source.Mode{source.ModeHTMLFetch, source.ModeBrowserVerify}, Priority: 78},
		"newegg":             {ID: "newegg", Name: "Newegg", Domains: []string{"newegg.com"}, SearchTemplate: "https://www.newegg.com/p/pl?d={query}", Modes: []source.Mode{source.ModeHTMLFetch, source.ModeBrowserVerify}, Priority: 86},
		"micro_center":       {ID: "micro_center", Name: "Micro Center", Domains: []string{"microcenter.com"}, SearchTemplate: "https://www.microcenter.com/search/search_results.aspx?Ntt={query}", Modes: []source.Mode{source.ModeHTMLFetch, source.ModeBrowserVerify}, Priority: 84},
		"bh_photo":           {ID: "bh_photo", Name: "B&H Photo", Domains: []string{"bhphotovideo.com"}, SearchTemplate: "https://www.bhphotovideo.com/c/search?q={query}", Modes: []source.Mode{source.ModeHTMLFetch, source.ModeBrowserVerify}, Priority: 84},
		"adorama":            {ID: "adorama", Name: "Adorama", Domains: []string{"adorama.com"}, SearchTemplate: "https://www.adorama.com/l/?searchinfo={query}", Modes: []source.Mode{source.ModeHTMLFetch, source.ModeBrowserVerify}, Priority: 80},
		"macys":              {ID: "macys", Name: "Macy's", Domains: []string{"macys.com"}, SearchTemplate: "https://www.macys.com/shop/featured/{query}", Modes: []source.Mode{source.ModeHTMLFetch, source.ModeBrowserVerify}, Priority: 78},
		"nordstrom":          {ID: "nordstrom", Name: "Nordstrom", Domains: []string{"nordstrom.com"}, SearchTemplate: "https://www.nordstrom.com/sr?keyword={query}", Modes: []source.Mode{source.ModeHTMLFetch, source.ModeBrowserVerify}, Priority: 78},
		"kohls":              {ID: "kohls", Name: "Kohl's", Domains: []string{"kohls.com"}, SearchTemplate: "https://www.kohls.com/search.jsp?submit-search=web-regular&search={query}", Modes: []source.Mode{source.ModeHTMLFetch, source.ModeBrowserVerify}, Priority: 76},
		"jcpenney":           {ID: "jcpenney", Name: "JCPenney", Domains: []string{"jcpenney.com"}, SearchTemplate: "https://www.jcpenney.com/g/search?searchTerm={query}", Modes: []source.Mode{source.ModeHTMLFetch, source.ModeBrowserVerify}, Priority: 74},
		"old_navy":           {ID: "old_navy", Name: "Old Navy", Domains: []string{"oldnavy.gap.com"}, SearchTemplate: "https://oldnavy.gap.com/browse/search.do?searchText={query}", Modes: []source.Mode{source.ModeHTMLFetch, source.ModeBrowserVerify}, Priority: 74},
		"gap":                {ID: "gap", Name: "Gap", Domains: []string{"gap.com"}, SearchTemplate: "https://www.gap.com/browse/search.do?searchText={query}", Modes: []source.Mode{source.ModeHTMLFetch, source.ModeBrowserVerify}, Priority: 72},
		"nike":               {ID: "nike", Name: "Nike", Domains: []string{"nike.com"}, SearchTemplate: "https://www.nike.com/w?q={query}", Modes: []source.Mode{source.ModeHTMLFetch, source.ModeBrowserVerify}, Priority: 80},
		"adidas":             {ID: "adidas", Name: "Adidas", Domains: []string{"adidas.com"}, SearchTemplate: "https://www.adidas.com/us/search?q={query}", Modes: []source.Mode{source.ModeHTMLFetch, source.ModeBrowserVerify}, Priority: 80},
		"under_armour":       {ID: "under_armour", Name: "Under Armour", Domains: []string{"underarmour.com"}, SearchTemplate: "https://www.underarmour.com/en-us/search/?q={query}", Modes: []source.Mode{source.ModeHTMLFetch, source.ModeBrowserVerify}, Priority: 78},
		"rei":                {ID: "rei", Name: "REI", Domains: []string{"rei.com"}, SearchTemplate: "https://www.rei.com/search?q={query}", Modes: []source.Mode{source.ModeHTMLFetch, source.ModeBrowserVerify}, Priority: 82},
		"ebay":               {ID: "ebay", Name: "eBay", Domains: []string{"ebay.com"}, SearchTemplate: "https://www.ebay.com/sch/i.html?_nkw={query}", Modes: []source.Mode{source.ModeAPI, source.ModeHTMLFetch}, Priority: 80, Marketplace: true, AffiliateCapable: true},
		"etsy":               {ID: "etsy", Name: "Etsy", Domains: []string{"etsy.com"}, SearchTemplate: "https://www.etsy.com/search?q={query}", Modes: []source.Mode{source.ModeHTMLFetch, source.ModeBrowserVerify}, Priority: 80, Marketplace: true},
		"aliexpress":         {ID: "aliexpress", Name: "AliExpress", Domains: []string{"aliexpress.com"}, SearchTemplate: "https://www.aliexpress.com/wholesale?SearchText={query}", Modes: []source.Mode{source.ModeHTMLFetch, source.ModeBrowserVerify}, Priority: 55, Marketplace: true},
		"temu":               {ID: "temu", Name: "Temu", Domains: []string{"temu.com"}, SearchTemplate: "https://www.temu.com/search_result.html?search_key={query}", Modes: []source.Mode{source.ModeHTMLFetch, source.ModeBrowserVerify}, Priority: 50, Marketplace: true},
		"alibaba":            {ID: "alibaba", Name: "Alibaba", Domains: []string{"alibaba.com"}, SearchTemplate: "https://www.alibaba.com/trade/search?SearchText={query}", Modes: []source.Mode{source.ModeHTMLFetch, source.ModeBrowserVerify}, Priority: 50, Marketplace: true},
		"autozone":           {ID: "autozone", Name: "AutoZone", Domains: []string{"autozone.com"}, SearchTemplate: "https://www.autozone.com/searchresult?searchText={query}", Modes: []source.Mode{source.ModeHTMLFetch, source.ModeBrowserVerify}, Priority: 84},
		"oreilly_auto":       {ID: "oreilly_auto", Name: "O'Reilly Auto Parts", Domains: []string{"oreillyauto.com"}, SearchTemplate: "https://www.oreillyauto.com/search?q={query}", Modes: []source.Mode{source.ModeHTMLFetch, source.ModeBrowserVerify}, Priority: 82},
		"advance_auto_parts": {ID: "advance_auto_parts", Name: "Advance Auto Parts", Domains: []string{"shop.advanceautoparts.com"}, SearchTemplate: "https://shop.advanceautoparts.com/find?searchTerm={query}", Modes: []source.Mode{source.ModeHTMLFetch, source.ModeBrowserVerify}, Priority: 80},
		"napa_auto":          {ID: "napa_auto", Name: "NAPA Auto Parts", Domains: []string{"napaonline.com"}, SearchTemplate: "https://www.napaonline.com/en/search?text={query}", Modes: []source.Mode{source.ModeHTMLFetch, source.ModeBrowserVerify}, Priority: 80},
		"rockauto":           {ID: "rockauto", Name: "RockAuto", Domains: []string{"rockauto.com"}, SearchTemplate: "https://www.rockauto.com/en/catalog/?partsearch={query}", Modes: []source.Mode{source.ModeHTMLFetch, source.ModeBrowserVerify}, Priority: 74},
	}
	collections := map[string]source.Collection{
		"tools":        {ID: "tools", Label: "Tools & hardware", Description: "Tools, hardware, jobsite equipment, power tools, lawn/farm utility, and shop gear.", DefaultSources: []string{"home_depot", "lowes", "harbor_freight", "ace_hardware", "tractor_supply", "ebay"}, ExtendedSources: []string{"menards", "northern_tool", "grainger", "mcmaster_carr", "zoro", "walmart", "amazon_api"}, MaxSources: 5},
		"office":       {ID: "office", Label: "Office supplies", Description: "Office supplies, business equipment, desks, printers, and workplace essentials.", DefaultSources: []string{"staples", "office_depot", "walmart", "target", "amazon_api"}, ExtendedSources: []string{"best_buy"}, MaxSources: 5},
		"electronics":  {ID: "electronics", Label: "Electronics", Description: "Consumer electronics, computers, cameras, accessories, gaming hardware, and appliances-adjacent tech.", DefaultSources: []string{"best_buy", "newegg", "micro_center", "bh_photo", "walmart"}, ExtendedSources: []string{"adorama", "target", "costco", "ebay", "amazon_api"}, MaxSources: 5},
		"clothing":     {ID: "clothing", Label: "Clothing", Description: "Apparel, shoes, sportswear, and department-store clothing.", DefaultSources: []string{"macys", "nordstrom", "kohls", "target", "nike"}, ExtendedSources: []string{"jcpenney", "old_navy", "gap", "adidas", "under_armour", "rei", "walmart", "ebay"}, MaxSources: 5},
		"marketplaces": {ID: "marketplaces", Label: "Marketplaces", Description: "Broad marketplaces for price checks, handmade goods, imports, and long-tail inventory.", DefaultSources: []string{"ebay", "etsy", "walmart", "amazon_api"}, ExtendedSources: []string{"aliexpress", "temu", "alibaba"}, MaxSources: 5},
		"auto":         {ID: "auto", Label: "Auto parts & accessories", Description: "Automotive parts, fluids, accessories, maintenance, and repair items.", DefaultSources: []string{"autozone", "oreilly_auto", "advance_auto_parts", "napa_auto", "rockauto"}, ExtendedSources: []string{"walmart", "ebay", "amazon_api"}, MaxSources: 5},
		"toys":         {ID: "toys", Label: "Toys & games", Description: "Toys, games, kids gifts, and family entertainment.", DefaultSources: []string{"target", "walmart", "best_buy", "costco", "ebay"}, ExtendedSources: []string{"amazon_api"}, MaxSources: 5},
		"gifts":        {ID: "gifts", Label: "Gifts", Description: "General gifts, handmade goods, marketplaces, and broad retail options.", DefaultSources: []string{"etsy", "target", "ebay", "walmart"}, ExtendedSources: []string{"costco", "amazon_api"}, MaxSources: 5},
	}
	return source.Registry{Sources: sources, Collections: collections}
}
